### ISSUE TITLE
Using old Python3* cmake modules

### ISSUE THREAD

**Issue by thopiekar** [PySide/shiboken2#10]
While fighting for hours and getting crazy searching I found an old copy of Python3Interp, etc. In the cmake directory. These files were probably needed in the days where Python was fresh and hip, but upstream PythonInterp can also find Python versions higher than 2.

Started making some cleanups and the only missing variable in upstream PythonInterp is Python_Library_with_debug I just wonder why this is needed, eg. when making non-debug builds for example.

**Comment by thopiekar** [comment]
I've made some little tests with my changes, but there is just a question left.
It's about this line: https://github.com/PySide/shiboken2/blob/master/CMakeLists.txt#L20
Is USE_PYTHON3 still needed? Could I replace it with something else, eg. USE_PYTHON=X.Y.Z?

**Comment by ctismer** [comment]
Not sure about this question. Since Python3 is supported, there was a distinction between py2 and py3 code. That is a general distinction, unless you can manage to write version-independent code.
I would very much appreciate that, but before going that path, you need to prove that you have version-independent code for all cases (it is ok to support py2.7 only, and 3.4 and up).

You can, for instance, require the six package or something similar, to make it simpler. I'm totally fine with it. But if you are not experienced in writing portable code, please don't try it on PySide2. ;-)

**Comment by thopiekar** [comment]
I just browsed the pyside2-setup repo for USE_PYTHON3 and it seems nothing is using it. https://github.com/PySide/pyside2-setup/search?utf8=%E2%9C%93&q=USE_PYTHON3
It also doesn't appear on other repositories. I'll make some test in my PPA as soon as possible.

**Comment by ctismer** [comment]
It does not. Still, I don't understand the code and hesitate to remove it.
If not set, we get at least python2.6, if set we get at least python3.3 .

I would prefer that just the python is used that is passed in via the setup.py script.
Can you propose a change? Or do we just close the issue (it works...) ?

**Comment by thopiekar** [comment]
Does it not work without "-DUSE_PYTHON3=ON"? So far as I remember cmake has python3 support and this code is not needed anymore.

**Comment by ctismer** [comment]
I was not eager to try that out, if the right Python would be grabbed etc.
That is what you would need to find out/make sure.
It can be re-written to use exactly the python it was started with. But what if debug is required?
I won't open a can of worms until somebody does an exhaustive test.
